# Site settings
title: Cornell MAE Undergraduate Program
description: Welcome to the official github page of the Cornell MAE Undergraduate Program. 
baseurl: "" 
url: "Cornell-MAE-UG.github.io" 

# Author settings
author:
  name: Cornell MAE Associate Director for UG Affairs
  email: mae-adua@cornell.edu

# Build settings
markdown: kramdown
theme: minimal-mistakes # The default theme for Jekyll, can be changed to another theme
plugins:

# Permalinks
permalink: /:categories/:title/

# Jekyll defaults
defaults:
  - scope:
      path: "" 
    values:
      layout: "default"
