# Site settings
title: Cornell MAE Undergraduate Program
description: Welcome to the official github page of the Cornell MAE Undergraduate Program. 
baseurl: "" 
url: "Cornell-MAE-UG.github.io" 

# Build settings
remote_theme: "mmistakes/minimal-mistakes" # Uses the Minimal Mistakes theme from GitHub
plugins:
  - jekyll-remote-theme # Needed to use remote themes on GitHub Pages
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache 

# Optional: Configure additional settings
markdown: kramdown
theme: minima
